# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cronjobs
# spec:
#   destination:
#     name: in-cluster
#     namespace: default
#   source:
#     path: cronjobs/
#     repoURL: 'https://github.com/akuity/examples'
#     targetRevision: HEAD
#   project: default