apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-plugin
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: applicationset-hello-plugin
    name: kind
  project: default
  source:
    path: ./
    repoURL: https://github.com/argoproj-labs/applicationset-hello-plugin
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true