apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-prometheus
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
        - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
  template:
    metadata:
      name: "{{.name}}-prometheus"
      labels:
        cluster_name: "{{.name}}"
    spec:
      project: default
      destination:
        name: '{{.name}}'
        namespace: prometheus
      sources:
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus
        targetRevision: 15.7.1
        helm:
          valueFiles:
          - '$values/applicationsets/prometheus/values-{{ (splitList "-" .name | first) }}.yaml'
          # - '$values/applicationsets/prometheus/values-{{ index .metadata.labels "provider" }}.yaml'
          # values: |
          #   server:
          #     global:
          #       external_labels:
          #         cluster: "{{.name}}"
          parameters:
            - name: "server.global.external_labels.cluster"
              value: "{{.name}}"
      - repoURL: 'https://github.com/akuity/examples.git'
        targetRevision: HEAD
        ref: values