apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-prometheus
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
  template:
    metadata:
      name: "{{name}}-prometheus"
      labels:
        cluster_name: "{{name}}"
    spec:
      project: default
      destination:
        name: '{{name}}'
        namespace: prometheus
      sources:
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus
        targetRevision: 15.7.1
        helm:
          valueFiles:
          - "$values/applicationsets/prometheus/values-{{ metadata.labels.provider }}.yaml"
          values: |
            server:
              global:
                external_labels:
                  cluster: "{{name}}"
            alertmanager:
              enabled: false
            # serverFiles:
            #   alerting_rules.yml:
            #     groups:
            #       - name: Instances
            #         rules:
            #           - alert: InstanceDown on {{ name }}
            #             expr: up == 0
            #             for: 5m
            #             labels:
            #               severity: page
            #             annotations:
            #               description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
            #               summary: 'Instance {{ $labels.instance }} down'
          # parameters:
          #   - name: "serverFiles.prometheus\\.yml.global.external_labels.cluster"
          #     value: "{{name}}"
      - repoURL: 'https://github.com/akuity/examples.git'
        targetRevision: HEAD
        ref: values