rbac:
  create: false
server:
  image:
    repository: quay.io/akuity/akuity
  podLabels:
    dc: "label-from-values-file"
serverFiles:
  alerting_rules.yml:
    groups:
      - name: Instances
        rules:
          - alert: InstanceDown on {{ $externalLabels.cluster }}
            expr: up == 0
            for: 5m
            labels:
              severity: page
            annotations:
              description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
              summary: 'Instance {{ $labels.instance }} down'